name: spring-microservices-library-app
services:
  db:
    container_name: library-microservices-postgres-db
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - ./sonar-init:/docker-entrypoint-initdb.d
    networks:
      - library-microservices-network

  pgAdmin4:
    image: dpage/pgadmin4
    container_name: my-pgadmin
    depends_on:
      - db
    ports:
      - "4040:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - library-microservices-network

  identity-service:
    image: ghcr.io/mariusss11/identity-service:latest
    depends_on:
      - db
    environment:
      DB_HOST: db
    ports:
      - "8050:8050"
    restart: unless-stopped
    networks:
      - library-microservices-network

  map-service:
    container_name: map-service
    image: ghcr.io/mariusss11/map-service:latest
    depends_on:
      - db
    environment:
      DB_HOST: db
    ports:
      - "8020:8020"
    networks:
      - library-microservices-network

  borrow-service:
    container_name: borrow-service
    image: ghcr.io/mariusss11/borrow-service:latest
    depends_on:
      - identity-service
      - map-service
      - db
    environment:
      DB_HOST: db
    ports:
      - "8030:8030"
    networks:
      - library-microservices-network

  frontend:
    image: ghcr.io/mariusss11/frontend:latest
    ports:
      - "5173:5173"
    restart: unless-stopped
    networks:
      - library-microservices-network

networks:
  library-microservices-network:
    driver: bridge

volumes:
  pgadmin-data:
  db:
  db_data:
