CREATE SCHEMA IF NOT EXISTS review;

CREATE TABLE reviews (
    review_id SERIAL PRIMARY KEY,
    client_id int NOT NULL,
    item_id int NOT NULL,
    comment VARCHAR(500) NOT NULL,
    rating INT CHECK (rating BETWEEN 1 AND 10) NOT NULL,
    is_anonymous BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_enabled BOOLEAN DEFAULT TRUE NOT NULL
);