apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-service-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres?currentSchema=auth
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: admin
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  ALLOWED_ORIGINS: "http://a312ebdfe078b4941b8ca485894409f4-891584174.eu-central-1.elb.amazonaws.com"
  BORROW_SERVICE: borrow-service:8030
  CLIENT_SERVICE: client-service:8010
  ITEM_SERVICE: item-service:8020
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
        - name: identity-service
          image: ghcr.io/mariusss11/identity-service:latest
          ports:
            - containerPort: 8050
          env:
            - name: DB_HOST
              value: "postgres"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: identity-service-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: identity-service-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: identity-service-config
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: identity-service-config
                  key: SPRING_KAFKA_BOOTSTRAP_SERVERS
            - name: ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: identity-service-config
                  key: ALLOWED_ORIGINS
            - name: BORROW_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: identity-service-config
                  key: BORROW_SERVICE
            - name: CLIENT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: identity-service-config
                  key: CLIENT_SERVICE
            - name: ITEM_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: identity-service-config
                  key: ITEM_SERVICE
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: login-secrets
                  key: ADMIN_USERNAME
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: login-secrets
                  key: ADMIN_PASSWORD
            - name: LIBRARIAN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: login-secrets
                  key: LIBRARIAN_USERNAME
            - name: LIBRARIAN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: login-secrets
                  key: LIBRARIAN_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  selector:
    app: identity-service
  ports:
    - protocol: TCP
      port: 8050
      targetPort: 8050
