apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: item-service
  template:
    metadata:
      labels:
        app: item-service
    spec:
      containers:
        - name: item-service
          image: ghcr.io/mariusss11/item-service:latest
          ports:
            - containerPort: 8020
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: item-service-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: item-service-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: item-service-config
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: item-service-config
                  key: SPRING_KAFKA_BOOTSTRAP_SERVERS
            - name: ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: identity-service-config
                  key: ALLOWED_ORIGINS
            - name: BORROW_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: item-service-config
                  key: BORROW_SERVICE

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: item-service-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres?currentSchema=item
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: admin
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  ALLOWED_ORIGINS: "http://a312ebdfe078b4941b8ca485894409f4-891584174.eu-central-1.elb.amazonaws.com"
  BORROW_SERVICE: borrow-service
---
apiVersion: v1
kind: Service
metadata:
  name: item-service
spec:
  selector:
    app: item-service
  ports:
    - protocol: TCP
      port: 8020
      targetPort: 8020
