# login-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: login-secrets
type: Opaque
stringData:
  ADMIN_USERNAME: admin@gmail.com
  ADMIN_PASSWORD: admin
  LIBRARIAN_USERNAME: librarian@gmail.com
  LIBRARIAN_PASSWORD: librarian
