apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
  labels:
    app: review-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
        - name: review-service
          image: ghcr.io/mariusss11/review-service:latest
          ports:
            - containerPort: 8060
          env:
            - name: SPRING_APPLICATION_NAME
              value: review-service
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: admin
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/postgres?currentSchema=review
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: validate
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "localhost:29092"
            - name: SERVER_PORT
              value: "8060"
            - name: SERVICES_BORROWSERVICE
              value: "borrow-service"
            - name: SERVICES_AUTHSERVICE
              value: "identity-service"
            - name: SERVICES_ITEMSERVICE
              value: "item-service"
            - name: SERVICES_CLIENTSERVICE
              value: "client-service"
            - name: SPRING_FLYWAY_LOCATIONS
              value: classpath:db/migration
            - name: SPRING_FLYWAY_SCHEMAS
              value: review
            - name: ALLOWED_ORIGINS
              value: "http://a312ebdfe078b4941b8ca485894409f4-891584174.eu-central-1.elb.amazonaws.com"
---
apiVersion: v1
kind: Service
metadata:
  name: review-service
spec:
  selector:
    app: review-service
  ports:
    - protocol: TCP
      port: 8060
      targetPort: 8060