spring:
  application:
    name: map-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "${SUPABASE_JDBC_URL}"
    username: "${SUPABASE_DATABASE_USER}"
    password: "${SUPABASE_DATABASE_PASSWORD}"
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 20000
      max-lifetime: 300000
      connection-timeout: 30000
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8020

secretsJwtString: "${JWT_SECRET}"
cors:
  allowed-origins: "${ALLOWED-ORIGINS}"

services:
  borrowService: "${BORROW_SERVICE:localhost:8030}"
