spring:
  application:
    name: identity-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: "${SUPABASE_DATABASE_USER}"
    password: "${SUPABASE_DATABASE_PASSWORD}"
    url: "${SUPABASE_JDBC_URL}"
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

cors:
  allowed-origins: "${ALLOWED_ORIGINS:http://localhost:80,http://localhost:81,http://localhost:5173}"

debug: true

logging:
  level:
    org.springframework.security: trace

services:
  borrowService: "${BORROW_SERVICE:localhost:8030}"
  itemService: "${ITEM_SERVICE:localhost:8020}"

#admin:
#  username: "${ADMIN_USERNAME:#{null}}"
#  password: "${ADMIN_PASSWORD:#{null}}"
#
#librarian:
#  username: "${LIBRARIAN_USERNAME:#{null}}"
#  password: "${LIBRARIAN_PASSWORD:#{null}}"


server:
  port: 8010

secretsJwtString: AM3N245B6BHJ43KSDFGHJKLM45N6B7VB7N6M54M5N6B