spring:
  application:
    name: identity-service
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://aws-1-eu-west-3.pooler.supabase.com:5432/postgres
#    username: postgres.ieovthbbdrdvlzhgcjkg
#    password: geodata_claude
    url: "${SUPABASE_JDBC_URL}"
    username: "${SUPABASE_DATABASE_USER}"
    password: "${SUPABASE_DATABASE_PASSWORD}"
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 20000
      max-lifetime: 300000
      connection-timeout: 30000
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.default_schema: auth
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: auth
    default-schema: auth
    create-schemas: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8010

secretsJwtString: "${JWT_SECRET}"
cors:
  allowed-origins: "${ALLOWED-ORIGINS}"


services:
  borrowService: "${BORROW_SERVICE:localhost:8030}"
