spring:
  application:
    name: review-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/postgres?currentSchema=review
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: "${BOOTSTRAP_SERVERS:localhost:29092}"
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  flyway:
    enable: true
    locations: classpath:db/migration
    schemas: review

server:
  port: 8060

logging:
  level:
    org.springframework.security: trace

cors:
  allowed-origins: "${ALLOWED_ORIGINS:http://localhost:80,http://localhost:81}"


services:
  borrowService: "${BORROW_SERVICE:localhost:8030}"
  authService: "${AUTH_SERVICE:localhost:8050}"
  itemService: "${ITEM_SERVICE:localhost:8020}"
  clientService: "${CLIENT_SERVICE:localhost:8010}"

secretsJwtString: AM3N245B6BHJ43KSDFGHJKLM45N6B7VB7N6M54M5N6B